### ISSUE TITLE
geolocation related null errors

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#623]
One, also happens on beta site, if you press the geolocation button quickly:

Uncaught TypeError: getGoogleMaps is not a function
    ConnectGeolocation ConnectGeolocation.js:30

Second, regression after #619, happens when switching geolocation off.
